apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: n6p987eoo-nodejs 
  janus-idp.io/tekton: n6p987eoo-nodejs
  backstage.io/kubernetes-id: n6p987eoo-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: n6p987eoo-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml