apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: n6p987eoo-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:8a26d98f78dc7473d76b511d9a9c75c461a3608e@sha256:db7caec274e6c3d3a94ac6da6d5883e4810a8985ad744b81e729b824b356beb3
          name: container-image
